workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Set up project
        script: |
          ls -la
          echo "Workspace exists:"
          ls -la Median.xcworkspace
      - name: Build IPA without signing
        script: |
          set -e
          xcodebuild -workspace Median.xcworkspace -scheme Median -sdk iphoneos -configuration Release -archivePath build/Median.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" archive
          mkdir -p build/Payload
          cp -R build/Median.xcarchive/Products/Applications/*.app build/Payload/
          cd build
          zip -r MoeElectric.ipa Payload
          ls -lh MoeElectric.ipa
          pwd
    artifacts:
      - build/MoeElectric.ipa
      - build/**/MoeElectric.ipa
      - MoeElectric.ipa
    publishing:
      email:
        recipients:
          - sohaibrawi90@gmail.com
